### ISSUE TITLE
gnomAD browser onboarding

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad_methods#461]
This epic is for onboarding new gnomAD browser developers and getting them familiar with each component of the codebase and infrastructure.

Checklist:

- [x] Create fresh deployment of the gnomAD cluster in a test environment
- [ ] Run the `gene` pipeline task on Dataproc
- [ ] Export gene data from Dataproc to Elasticsearch
- [ ] Run the API locally and query gene data
- [ ] Deploy new versions of the API and browser
- [ ] Understand the reads & blog deployments
- [ ] Learn how to load large datasets by scaling Elasticsearch
- [ ] Deploy a change to the production cluster
